[package]
name = "hassle-rs"
version = "0.3.0"
authors = ["Jasper-Bekkers <bekkers@gmail.com>"]
edition = "2018"
description = "HLSL compiler library, this crate provides an FFI layer and idiomatic rust wrappers for the new DXC hlsl compiler and validator."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Jasper-Bekkers/hassle-rs"
repository = "https://github.com/Jasper-Bekkers/hassle-rs"
keywords = ["shader", "pipeline", "hlsl", "dxc", "intellisense"]
categories = ["rendering", "rendering::graphics-api"]
include = [
    "src/*.rs",
    "src/intellisense/*.rs",
    "Cargo.toml",
]
documentation = "https://docs.rs/hassle-rs"

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[dependencies]
libloading = "0.5.2"
com-rs = "0.2.0"
winapi = "0.3.7"
bitflags = "1.1.0"

[dev-dependencies]
rspirv = "0.5.4"

[features]
default = ["winapi/wtypes", "winapi/oleauto"]